denoiser:
  target: mld.models.architectures.mld_denoiser.MldDenoiserV2
  params:
    text_dim: 768
    ff_size: 1024
    num_layers: 9
    num_heads: 4
    dropout: 0.1
    normalize_before: false
    activation: 'gelu'
    flip_sin_to_cos: true
    return_intermediate_dec: false
    position_embedding: 'learned'
    arch: 'trans_enc'
    freq_shift: 0
    latent_dim: ${model.latent_dim}
    time_embed_dim: 512
